name: challenge_1

on: [push, workflow_dispatch]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: print-date
        run: date
  job_2:
    runs-on: windows-latest
    steps:
      - name: print-date
        run: Get-Date
  job_3:
    runs-on: macos-latest
    steps:
      - name: print-date
        run: date
  job_4:
    runs-on: ubuntu-latest
    needs: [job_1, job_2, job_3]
    steps:
      - name: print-date
        run: date
