name: test_pull_request

on:
  pull_request:

jobs:
  test:
    name: test pull request
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Test
      run: mvn -B test --file pom.xml
    
