name: test_pull_request

on:
  pull_request:

jobs:
  setup:
  
    env:
      OWNER: dmgiangi
      REPO: test-actions
      REF: ${{GITHUB_REF}}
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn -B test --file pom.xml
        curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{secrets.token_github}} https://api.github.com/repos/${{env.OWNER}}/${{env.REPO}}/commits/${{env.REF}}/status
